version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/myblog
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-symfony
      - mysql-symfony
  
  php-symfony:
    container_name: php-symfony
    build:
      context: ./docker/php-symfony
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/myblog
    depends_on:
      - mysql-symfony

  mysql-symfony:
    platform: linux/x86_64
    container_name: mysql-symfony
    image: mysql:${MYSQL_VERSION:-8.0}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-myblog}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-ChangeMe}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ChangeMe}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql